### ISSUE TITLE
ICEE Presentation to Leads

### ISSUE THREAD

**Issue by kkale25** [ICPI/ICEE#2]
Please see below for the ICEE presentation for March 30. This is a draft and will be updated/finalized by COB today.

Please comment below with suggestions/edits.
[ICEE Presentations to Leads_03272018.pptx](https://github.com/ICPI/ICEE/files/1856726/ICEE.Presentations.to.Leads_03272018.pptx)

**Comment by kkale25** [comment]
Updated and edited presentation to Leads....close to final. 
[ICEE Presentations to Leads_03292018.pptx](https://github.com/ICPI/ICEE/files/1860908/ICEE.Presentations.to.Leads_03292018.pptx)

**Comment by jb3436** [comment]
This issue was moved to ICPI/Engagements#26
