### ISSUE TITLE
Feedback from Leads - March 30 Presentations 

### ISSUE THREAD

**Issue by kkale25** [ICPI/ICEE#4]
Please add your comments/thoughts/questions/solutions below. The feedback we received is attached below. I will reupdate this issue with the summary of the feedback shortly.

[Cluster Pres Fbk_ICEEteam_04092018.docx](https://github.com/ICPI/ICEE/files/1903433/Cluster.Pres.Fbk_ICEEteam_04092018.docx)

**Comment by jb3436** [comment]
This issue was moved to ICPI/Engagements#25
